[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo = "0.11.0"
pixels = "0.14.0"
wasm-bindgen-futures = "0.4.43"
web-sys = { version = "0.3.70", features = ["Document", "Element", "HtmlBodyElement", "Window"] }
winit = "0.30.5"
